/// AI analysis report generated by the Feynman Technique evaluation.
///
/// Contains a numeric score, identified knowledge gaps, jargon
/// violations, and suggested analogies.
class AiReport {
  final double score;
  final List<Gap> gaps;
  final List<Jargon> jargon;
  final List<Analogy> analogies;

  const AiReport({
    required this.score,
    this.gaps = const [],
    this.jargon = const [],
    this.analogies = const [],
  });

  /// Parses an [AiReport] from the JSON map returned by the AI model.
  factory AiReport.fromJson(Map<String, dynamic> json) {
    return AiReport(
      score: (json['score'] as num?)?.toDouble() ?? 0.0,
      gaps: (json['gaps'] as List<dynamic>?)
              ?.map((e) => Gap.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      jargon: (json['jargon'] as List<dynamic>?)
              ?.map((e) => Jargon.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      analogies: (json['analogies'] as List<dynamic>?)
              ?.map((e) => Analogy.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'score': score,
      'gaps': gaps.map((g) => g.toJson()).toList(),
      'jargon': jargon.map((j) => j.toJson()).toList(),
      'analogies': analogies.map((a) => a.toJson()).toList(),
    };
  }

  @override
  String toString() =>
      'AiReport(score: $score, gaps: ${gaps.length}, jargon: ${jargon.length}, analogies: ${analogies.length})';
}

/// A knowledge gap detected in the student's explanation.
class Gap {
  final String title;
  final String detail;

  const Gap({required this.title, required this.detail});

  factory Gap.fromJson(Map<String, dynamic> json) {
    return Gap(
      title: json['title'] as String? ?? '',
      detail: json['detail'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() => {'title': title, 'detail': detail};

  @override
  String toString() => 'Gap(title: $title)';
}

/// A jargon term that is too advanced for the target audience.
class Jargon {
  final String word;
  final String suggestion;

  const Jargon({required this.word, required this.suggestion});

  factory Jargon.fromJson(Map<String, dynamic> json) {
    return Jargon(
      word: json['word'] as String? ?? '',
      suggestion: json['suggestion'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() => {'word': word, 'suggestion': suggestion};

  @override
  String toString() => 'Jargon(word: $word)';
}

/// A real-world analogy suggestion to improve the explanation.
class Analogy {
  final String topic;
  final String analogy;

  const Analogy({required this.topic, required this.analogy});

  factory Analogy.fromJson(Map<String, dynamic> json) {
    return Analogy(
      topic: json['topic'] as String? ?? '',
      analogy: json['analogy'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() => {'topic': topic, 'analogy': analogy};

  @override
  String toString() => 'Analogy(topic: $topic)';
}
